### PR TITLE
Aug 977/multi select dropdown style

### PR DESCRIPTION
**Pull request by bakesaled**
**JIRA**
https://jira.inbcu.com/browse/AUG-977

***Changes include:***
- Combining functionality of select-search and dropdown-select into a single 'select' component.
- Virtual Scroll Component added to handle large datasets.  In the future could add configurable page sizes, but for now, simply reloads the visible items as you scroll.
- The choice to use either a collection of Option Components or an OptionList Component that supports virtual scrolling and custom templates.
- Supports images (32x32) and icons.
- Can specify a text-only activation button.
- Re-styled to match the mocks.
- Support for reactive forms - validate, disable, etc.
- Single and multi-select modes
- Search box
- Uses the popup directive to share standardized popup behaviors with other components.

image

image

### CODE REVIEW

**Comment by bcandullo** [comment]
I am getting a floating menu (.Popup-panel) when scrolling after opening the menu. Maybe we could bind document scroll/click to auto close the menu? If not, having the menu positioned relative to the activation component like an OS <select> would work.

screen shot 2017-11-28 at 12 58 07 pm

Other than that this looks great.

**Comment by bakesaled** [comment]
Yep, that is annoying.  I can add a div underneath the popup that will deal with scrolling and react to clicks.  I was trying to avoid z-index conflicts by placing the popup at the bottom of the dom.

**Comment by bakesaled** [comment]
Thanks @paulkahle !
1. Mouseleave is already configurable.  I can just remove the event handler.
2. Scrolling is a little trickier.  But I believe it can be added back in.
3. The easiest way to reduce the flicker is to configure a larger page size.  Rather than reloading on every scroll, it would just reload when you reach 200 items, for example.  I'll make this configurable.

I guess I've always operated under the theory that popups should be placed either before the </body> or right after the <body>.  I've seen issues in the past with positioning and z-index conflicts when multiple popups are nested inside the dom flow.  For example, if I put a dropdown-menu inside a modal, I get a clipped menu popup:

image

Styling is trickier but I think you have more control.  Instead of inheriting unwanted CSS, specific styles can be transferred from the trigger through template binding and a little script.  For example, for font-size in the select component:
```html
<div class="Select-panel"
       [ngClass]="{'Select-panel--small': triggerSmall}"
       [style.transformOrigin]="'top'"
       [style.font-size.px]="triggerFontSize">
      <ng-content></ng-content>
  </div>
```
```
this.triggerFontSize = parseInt(
      getComputedStyle(this.trigger.nativeElement)['font-size'],
      0
    );
```
Still I can see the trade-offs both ways.  If you'd prefer, I'd be happy to move the popup back into the DOM flow.

**Comment by paulkahle** [comment]
@bakesaled 
I think if you use `position:fixed` you won't have those issues with clipping.  If you look at our tooltips in the grid for example they use `position:fixed' and don't get clipped when a parent has `overflow:hidden`.

**Comment by bakesaled** [comment]
@paulkahle 
I was able to make all the requested changes.  A couple things to note:
1. These changes also affect the date-range-input since it uses the same popup control.  I removed the mouseleave close() event from this popup as well.  mouseleave is configurable per component, so I can always put it back for this one.
2. By placing the popup inside the DOM flow, I've noticed one side-effect.  Notice the bleed-through of the text from the bottom select:

image

**Comment by paulkahle** [comment]
@bakesaled 
This is looking awesome.  All you need to do to fix the bleed issue is to add a z-index to the Popup-container. $z-index-popover?

**Comment by paulkahle** [comment]
@bakesaled.  One more thing.  Can you make the option hover bg match the basic button hover bg, and the selected option bg match the basic button is-down bg?  Make sure the selected style takes precedence over the hover style so the color doesn't change when hovering over the selected item.

**Comment by bakesaled** [comment]
@paulkahle 
z-index worked!  It also fixed an issue @craigmichaelmartin was having with the old dropdowns inside a modal.

**Pull request merged**
